name: Checkov Scan

on:
  push:
    branches: [main]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov
      run: checkov -d .
