name: Trivy Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.tar.gz
        tar -xzf trivy_0.50.1_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/

    - name: Scan source for vulnerabilities
      run: trivy fs . --severity CRITICAL,HIGH --no-progress

